name: Daily Reminder

on:
  schedule:
    - cron: "05 13 * * *"  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Render app (with retry)
        run: |
          for i in 1 2 3; do
            curl -X POST https://event-app10.onrender.com/cron_reminder && break
            echo "Retrying in 5 seconds..."
            sleep 5
          done
